# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      addresses:
      - 172.16.1.20/24
      gateway4: 172.16.1.254
      nameservers:
        addresses:
        - 172.16.10.254
        search:
        - pti.intra
  version: 2
